# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import model_pb2 as model__pb2


class ModelStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.classify = channel.unary_unary(
        '/cppservice.Model/classify',
        request_serializer=model__pb2.IrisDataFrame.SerializeToString,
        response_deserializer=model__pb2.ClassifyOut.FromString,
        )


class ModelServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def classify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ModelServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'classify': grpc.unary_unary_rpc_method_handler(
          servicer.classify,
          request_deserializer=model__pb2.IrisDataFrame.FromString,
          response_serializer=model__pb2.ClassifyOut.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cppservice.Model', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
