# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model.proto',
  package='cppservice',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmodel.proto\x12\ncppservice\"e\n\rIrisDataFrame\x12\x14\n\x0csepal_length\x18\x01 \x03(\x01\x12\x13\n\x0bsepal_width\x18\x02 \x03(\x01\x12\x14\n\x0cpetal_length\x18\x03 \x03(\x01\x12\x13\n\x0bpetal_width\x18\x04 \x03(\x01\"\x1c\n\x0b\x43lassifyOut\x12\r\n\x05value\x18\x01 \x03(\x03\x32G\n\x05Model\x12>\n\x08\x63lassify\x12\x19.cppservice.IrisDataFrame\x1a\x17.cppservice.ClassifyOutb\x06proto3')
)




_IRISDATAFRAME = _descriptor.Descriptor(
  name='IrisDataFrame',
  full_name='cppservice.IrisDataFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sepal_length', full_name='cppservice.IrisDataFrame.sepal_length', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sepal_width', full_name='cppservice.IrisDataFrame.sepal_width', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='petal_length', full_name='cppservice.IrisDataFrame.petal_length', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='petal_width', full_name='cppservice.IrisDataFrame.petal_width', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=128,
)


_CLASSIFYOUT = _descriptor.Descriptor(
  name='ClassifyOut',
  full_name='cppservice.ClassifyOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='cppservice.ClassifyOut.value', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['IrisDataFrame'] = _IRISDATAFRAME
DESCRIPTOR.message_types_by_name['ClassifyOut'] = _CLASSIFYOUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IrisDataFrame = _reflection.GeneratedProtocolMessageType('IrisDataFrame', (_message.Message,), dict(
  DESCRIPTOR = _IRISDATAFRAME,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:cppservice.IrisDataFrame)
  ))
_sym_db.RegisterMessage(IrisDataFrame)

ClassifyOut = _reflection.GeneratedProtocolMessageType('ClassifyOut', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYOUT,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:cppservice.ClassifyOut)
  ))
_sym_db.RegisterMessage(ClassifyOut)



_MODEL = _descriptor.ServiceDescriptor(
  name='Model',
  full_name='cppservice.Model',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=160,
  serialized_end=231,
  methods=[
  _descriptor.MethodDescriptor(
    name='classify',
    full_name='cppservice.Model.classify',
    index=0,
    containing_service=None,
    input_type=_IRISDATAFRAME,
    output_type=_CLASSIFYOUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODEL)

DESCRIPTOR.services_by_name['Model'] = _MODEL

# @@protoc_insertion_point(module_scope)
